### ISSUE TITLE
Wrong URL

### ISSUE THREAD

**Issue by Hribek25** [nuriel77/iri-playbook#103]
https://github.com/nuriel77/iri-playbook/blob/56feda980a3dd887df832197c546105ffc4be560/roles/iri/files/iric#L229

**Comment by Hribek25** [comment]
The following should be correct one
```https://github.com/iotaledger/iri/releases/download/v1.6.0-RELEASE/iri-1.6.0-RELEASE.jar```

**Comment by Hribek25** [comment]
here is the fix:
```
wget "https://github.com/iotaledger/iri/releases/download/v${IRI_LATEST_CLEAN}-RELEASE/iri-${IRI_LATEST}.jar" -O "$TFILE"
```

**Comment by nuriel77** [comment]
@Hribek25 , thanks. Was fixed here:
https://github.com/nuriel77/iri-playbook/commit/5779411651c13ca296411a7c6e9033ebd15e6475#diff-4cf7fa7877d5a23f6574bf01e9a338feR229

Hopefully they will not change it next time ;)
