### ISSUE TITLE
Multiple issues on CentOS 7.4

### ISSUE THREAD

**Issue by wblondel** [nuriel77/iri-playbook#11]
Hi,

Thanks for creating this playbook and writing this tutorial!

I have multiple issues with your playbook.

My machine: 
```
Operating System: CentOS Linux 7 (Core)
centos-release-7-4.1708.el7.centos.x86_64
CPE OS Name: cpe:/o:centos:centos:7
Kernel: Linux 3.10.0-693.11.1.el7.x86_64
Architecture: x86-64
```

First error:
```
TASK [iotapm : allow iotapm nginx port via selinux seport] **************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "This module requires policycoreutils-python"}
```
I had to install policycoreutils-python because the script doesn't do it.

Second error:
If SELinux is disabled, any tasks related to it fails. (SELinux is disabled by default by my VPS provider).
I enabled it.

Third error:
```
TASK [monitoring : create prometheus datasource in grafana] *************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "connection": "close", "content": "{\"message\":\"Invalid username or password\"}", "content_length": "42", "content_type": "application/json; charset=UTF-8", "date": "Wed, 13 Dec 2017 08:56:16 GMT", "failed": true, "json": {"message": "Invalid username or password"}, "msg": "Status code was not [200, 409]: HTTP Error 401: Unauthorized", "redirected": false, "status": 401, "url": "http://localhost:3000/api/datasources"}
```
I tried to hardcode my password into the script, it still doesn't work :/

**Comment by nuriel77** [comment]
Hi @wblondel thanks for the input. It is valuable so that the installer can take into account these different scenarios.

I will add 'policycoreutils-python' as a dependency before tasks relating to it are being used.

I will also ensure the installer has selinux enabled (I don't understand why the VPS provider disables it by default - bad practice).

Regarding the third error, did you have to enter a password when you ran the one-line command to install? (there was a prompt)

**Comment by wblondel** [comment]
I didn't follow the click-n-go installation, but the step-by-step guide.

I modified the password in `group_vars/all/iotapm.yml` (amongst other things) and ran the playbook as root.
I didn't have to input any other passwords.

**Comment by nuriel77** [comment]
Regarding the grafana access, try:
```sh
systemctl stop grafana-server
rm -f /var/lib/grafana/grafana.db /etc/grafana/grafana.ini
```
Then, ensure you have the  user/password you selected in group_vars/all/iotapm.yml this will also configure the grafana user/password.

Try to re-run the playbook's monitoring role:
```sh
cd /opt/iri-playbook && ansible-playbook -i inventory -v site.yml --tags=monitoring_role
```
You can check which user/password was configured:
```sh
grep ^admin /etc/grafana/grafana.ini
```

If this doesn't work, consider re-deploying your VPS, and running via the click-'n-go. I've already updated the Selinux issues: https://github.com/nuriel77/iri-playbook/commit/c1a243191d5779a4a52d36bff0a47a3a3ea0ce72

**Comment by wblondel** [comment]
Ok this is weird, I ran the first two commands you gave me, and changed my password in `group_vars/all/iotapm.yml` by a simpler one. I re-run the playbook entirely, and it worked !
Maybe it didn't like the special characters in my password ? I had some `#`  and `*`, now I only have some `*`.

**Comment by nuriel77** [comment]
If you use special characters in the yml configuration file it is best to put it inside single quotes, e.g:
```sh
my_pass: '2@!R_42<>[d2Cc3'
```
If you did it, it could be that grafana is not happy about special characters, or the ansible uri module. Not sure.

Anyway, I am glad it works now ;)

**Comment by wblondel** [comment]
Yes, it was in single quotes. 

And I think I know why it didn't work.

```
[root@iota-wgb iri-playbook]# grep ^admin /etc/grafana/grafana.ini
admin_user = iotapm
admin_password = hereisthepassword
```

If you put a password starting with '#', grafana will probably thinks it is a comment =)

Thanks for your help!

**Comment by nuriel77** [comment]
You are absolutely right: http://docs.grafana.org/installation/configuration/#password

I made a new commit to handle these special characters: https://github.com/nuriel77/iri-playbook/commit/cdc488ab1a45a2c234e191d6cc60d6631bae6a50
