### ISSUE TITLE
Selecting "cancel" on the remove neighbors screen still asks to remove a neighbor

### ISSUE THREAD

**Issue by rajivshah3** [nuriel77/iri-playbook#122]
## Description

When viewing the "remove neighbors" screen, selecting "cancel" leads to a prompt asking the user to confirm removal of the first neighbor in the list.

## Steps to reproduce
1. Start `iric`
2. Use arrow keys to select "Neighbors"
3. Use arrow keys to select "Remove neighbors"
4. Press right arrow key twice to select "Cancel" and press return/enter

## Screenshots
<img width="628" alt="Screen Shot 2020-05-05 at 1 06 05 PM" src="https://user-images.githubusercontent.com/19519564/81094326-5692ed00-8ed1-11ea-87be-5d71c77a21c2.png">
<img width="622" alt="Screen Shot 2020-05-05 at 1 06 37 PM" src="https://user-images.githubusercontent.com/19519564/81094327-5692ed00-8ed1-11ea-95fd-eb2bec3b6232.png">

**Comment by nuriel77** [comment]
fixed here https://github.com/nuriel77/iri-playbook/commit/3eebeb0728291fec8995599bb238134dff600d51

**Comment by rajivshah3** [comment]
Thanks, that was fast 😄
