### ISSUE TITLE
Issue on the Ubuntu Zesty Scaleway image

### ISSUE THREAD

**Issue by wblondel** [nuriel77/iri-playbook#14]
Hi,

I just tried to install the playbook on a Ubuntu Zesty image on Scaleway, it stopped at 
`TASK [iri : ensure ufw started]`
and it actually locked me out of the server. I can't connect anymore via SSH.

`ssh: connect to host ***** port 22: Operation timed out`

Looks like the script messed up the firewall configuration.

**Comment by nuriel77** [comment]
I tested with Ubuntu Zesty this image: https://cloud-images.ubuntu.com/releases/17.04/release/
(64 bit cloud image) and didn't have this issue.

If you look here, you'll see that the playbook is first ensuring that ssh port is allowed, only then enable ufw:
https://github.com/nuriel77/iri-playbook/blob/master/roles/iri/tasks/ufw.yml#L23
Which prevents this scenario.

Anyway, I've done some googling about ufw + scaleway. It seems that scaleway use nbd (network block device) and it might be the case that it is what is crashing the server/dropping the connection for you.

Have a look here:
https://community.online.net/t/how-to-configures-iptables-with-input-rules-with-dynamic-nbd/303/22

**Comment by nuriel77** [comment]
Added warning/notice for users about nbd firewall issue with Scaleway:
http://iri-playbook.readthedocs.io/en/master/getting-started-quickly.html#run-the-installer (below)

**Comment by christiangrieger** [comment]
This is the fix to get ufw running with scaleway baremetal servers :)

https://community.online.net/t/how-to-configures-iptables-with-input-rules-with-dynamic-nbd/303/22

Maybe it helps someone
