### ISSUE TITLE
Grafana didn´t get data after a time

### ISSUE THREAD

**Issue by valshare** [nuriel77/iri-playbook#24]
Hi,
first thanks for you great iri-playbook. I have installed it on a vps with 16GB RAM and 6 Cores on Ubuntu 16.04. The installation went very well. IRI and Iota-PM runs very stable. I have problem with grafana. Grafana gets data for a little time (1-x hours) from iri. After 1-x hours, there didnt flow any data from iri to grafana. CPU, Memory, etc will get data. Cant find the problem. Do you can help?

Valle

**Comment by nuriel77** [comment]
Depending on when you installed your server, there's been an update recently to the monitoring/graph.
Try to follow this update instruction here: http://iri-playbook.readthedocs.io/en/latest/maintenance.html#upgrade-iota-monitoring

**Comment by valshare** [comment]
Thanks, There was one update. Updated the monitoring/graph.

 

Von: Nuriel Shem-Tov <notifications@github.com>
Antworten an: nuriel77/iri-playbook <reply@reply.github.com>
Datum: Samstag, 16. Dezember 2017 um 08:56
An: nuriel77/iri-playbook <iri-playbook@noreply.github.com>
Cc: valshare <valshare2000@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [nuriel77/iri-playbook] Grafana didn´t get data after a time (#24)

 

Depending on when you installed your server, there's been an update recently to the monitoring/graph.
Try to follow this update instruction here: http://iri-playbook.readthedocs.io/en/latest/maintenance.html#upgrade-iota-monitoring

**Comment by valshare** [comment]
sorry, bit update didn´t help.
again i didn´t get data in grafana. This are the services that are listen and running.Are any missing?

<img width="1440" alt="grafik" src="https://user-images.githubusercontent.com/365861/34070951-9eea6af4-e26e-11e7-89b7-74bc247ba98d.png">

<img width="991" alt="grafik" src="https://user-images.githubusercontent.com/365861/34070954-add521ee-e26e-11e7-8479-d2dcb86588d9.png">

**Data from 12:56 till 14:40 are missing.**

<img width="1407" alt="grafik" src="https://user-images.githubusercontent.com/365861/34070962-ec0d707e-e26e-11e7-82e3-a33ea7fcdd39.png">

**Comment by nuriel77** [comment]
Hi. 
It looks like the iota-prom-exporter crashed.
You can check its logs:
```
journalctl --no-pager -u iota-prom-exporter
```
Paste the last 50 lines of output here (or in a gist)

Anyway, I am the upgrade might not have gone as expected, or service not restarted.

Just to be sure, please try the following:
```
systemctl stop iota-prom-exporter
```
then
```
rm -rf /opt/prometheus/iota-prom-exporter
```
and last:
```
cd /opt/iri-playbook/ && ansible-playbook -i inventory site.yml --tags=iota_prom_exporter -v
```

See how it is.
If again you see data stop, please try the journalctl again.

**Comment by valshare** [comment]
looks that nodejs is not running anymore. 

**After a reboot:**
  
<img width="825" alt="grafik" src="https://user-images.githubusercontent.com/365861/34071067-a4c6ea2c-e270-11e7-99fb-07eb0b1540f4.png">

<img width="1337" alt="grafik" src="https://user-images.githubusercontent.com/365861/34071065-9579e3d0-e270-11e7-8684-39bb0659ebcd.png">

**Comment by nuriel77** [comment]
yes, I've noticed. Hence my reply from above.

**Comment by valshare** [comment]
ok, after next crash ... i try you post above.

**Comment by nuriel77** [comment]
You can still try to provide the logs (the journalctl command) it can shed more light on what might have caused the crash. Thank you.

**Comment by valshare** [comment]
-- Logs begin at Sat 2017-12-16 14:47:05 CET, end at Sat 2017-12-16 14:55:15 CET. --
Dec 16 14:47:06 iota systemd[1]: Started IOTA Prometheus Exporter.
Dec 16 14:47:13 iota iota_exporter[221]: Listening on: 9311
Dec 16 14:47:13 iota iota_exporter[221]: Connected to Bitfinex websocket
Dec 16 14:47:17 iota iota_exporter[221]: TypeError: Value is not a valid number: undefined
Dec 16 14:47:17 iota iota_exporter[221]:     at /opt/prometheus/iota-prom-exporter/node_modules/prom-client/lib/gauge.js:219:10
Dec 16 14:47:17 iota iota_exporter[221]:     at Gauge.set (/opt/prometheus/iota-prom-exporter/node_modules/prom-client/lib/gauge.js:85:31)
Dec 16 14:47:17 iota iota_exporter[221]:     at getResults (/opt/prometheus/iota-prom-exporter/app.js:64:31)
Dec 16 14:47:17 iota iota_exporter[221]:     at <anonymous>
Dec 16 14:47:17 iota iota_exporter[221]:     at process._tickCallback (internal/process/next_tick.js:188:7)
Dec 16 14:47:22 iota iota_exporter[221]: TypeError: Value is not a valid number: undefined
Dec 16 14:47:22 iota iota_exporter[221]:     at /opt/prometheus/iota-prom-exporter/node_modules/prom-client/lib/gauge.js:219:10
Dec 16 14:47:22 iota iota_exporter[221]:     at Gauge.set (/opt/prometheus/iota-prom-exporter/node_modules/prom-client/lib/gauge.js:85:31)
Dec 16 14:47:22 iota iota_exporter[221]:     at getResults (/opt/prometheus/iota-prom-exporter/app.js:64:31)
Dec 16 14:47:22 iota iota_exporter[221]:     at <anonymous>
Dec 16 14:47:22 iota iota_exporter[221]:     at process._tickCallback (internal/process/next_tick.js:188:7)
Dec 16 14:54:36 iota systemd[1]: Stopping IOTA Prometheus Exporter...
Dec 16 14:54:36 iota systemd[1]: Stopped IOTA Prometheus Exporter.
Dec 16 14:55:13 iota systemd[1]: Started IOTA Prometheus Exporter.
Dec 16 14:55:14 iota systemd[1]: Stopping IOTA Prometheus Exporter...
Dec 16 14:55:14 iota systemd[1]: Stopped IOTA Prometheus Exporter.
Dec 16 14:55:14 iota systemd[1]: Started IOTA Prometheus Exporter.
Dec 16 14:55:15 iota iota_exporter[904]: Listening on: 9311
Dec 16 14:55:15 iota iota_exporter[904]: Connected to Bitfinex websocket

**Comment by nuriel77** [comment]
Yes, it looks like it crushed due to the bug that was fixed in the update.
I am guessing something with the updated didn't work as  expected.
Can you try:
```
git --git-dir=/opt/prometheus/iota-prom-exporter/.git describe HEAD --tags
```

**Comment by valshare** [comment]
it gives me:
v0.2-26-g6856dce

**Comment by nuriel77** [comment]
That's the latest. Bug already fixed. Maybe somehow the service didn't restart during previous update.
Please keep an eye on it if it crashes again let me know I will get in touch with the developer of this application.
