### ISSUE TITLE
Node not working

### ISSUE THREAD

**Issue by mensa84** [nuriel77/iri-playbook#31]
Was anyone of you able to get a working full node with iri-playbook?
I tried this on Ubuntu Server 17.10, Ubuntu Server 17.04 and also Ubuntu Server 16.04.3. But same problem on every installation:
[https://i.imgur.com/qQGXoUx.png](url)
Sent TX always stays at 1. Doesn't matter if "normal" neighbors or swarm nodes.
Any explanation or problem solving for that? Portforwarding is fine.

**Comment by nuriel77** [comment]
Can you please clarify the error?
It seems like a problem with neighbors rather than with the installation?

**Comment by mensa84** [comment]
Hello,
I try again to post the link. If it's again not working, please copy&paste the URL.
[https://i.imgur.com/qQGXoUx.png](https://i.imgur.com/qQGXoUx.png)
On that screenshot you can see the situation after all my 3 installations. "Sent TX" goes to 1 and stays there constant. Doesn't matter if "normal" neighbors or swarm nodes.
If I install after iota.partner guide or in windows my nodes are working correctly and with a lot of traffic.
But why not with iri-playbook?

**Comment by nuriel77** [comment]
I didn't hear from others about such problem.
Did you follow this instructions on a fresh installation? http://iri-playbook.readthedocs.io/en/master/getting-started-quickly.html

Also not that this installer does not download a fully synced database so you need at least 3-4 "healthy" neighbors.

Did the installation end successfully or where there errors?

**Comment by mensa84** [comment]
Yes did the quick start and installation was without problems.
I know, that db is not synced.
It does not solve the problem, sorry.

**Comment by nuriel77** [comment]
@mensa84 you can catch me on slack @nuriel77 we can try figure this out. I think this is a database/sync problem unrelated to the installer specifically.
