### ISSUE TITLE
iota:password line wasn't commented out

### ISSUE THREAD

**Issue by elktamer** [nuriel77/iri-playbook#32]
I was getting a 401 error from iota-pm and when I checked, the line in in the init config has the iota:password part uncommented, meaning you'd need to use authentication with curl, which the setup wasn't using.

**Comment by nuriel77** [comment]
Hi @elktamer . I am not sure where / what exactly you are referring to?
If you follow the Getting Started Quickly guide you are asked to choose a password with which to connect to iota-pm. This is all set automatically.

Can you paste examples of what you mean? It is a little vague atm I am afraid.

Thanks!

**Comment by nuriel77** [comment]
@elktamer sorry, I see now what you mean.
Fixed in this commit: https://github.com/nuriel77/iri-playbook/commit/13db87012deb373f0584686d394da9c03b89c3b9

Thanks again.
