### ISSUE TITLE
Iptables

### ISSUE THREAD

**Issue by johndomenic** [nuriel77/iri-playbook#41]
TASK [iri : allow iri tcp port in firewall] *******************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "ERROR: initcaps\n[Errno 2] iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)\nPerhaps iptables or your kernel needs to be upgraded.\n\n"}
	to retry, use: --limit @/opt/iri-playbook/site.retry

PLAY RECAP ****************************************************************************************************************************************************************
localhost                  : ok=9    changed=0    unreachable=0    failed=1

**Comment by johndomenic** [comment]
Tried to look up this issue everywhere online ... couldn't figure out what the hell is going on with the iptables. I'm running on windows 10 office.

**Comment by nuriel77** [comment]
http://iri-playbook.readthedocs.io/en/master/requirements.html#operating-system

In the above link is a list of supported operating systems. Windows is not supported.
