### ISSUE TITLE
Add multipe nodes.

### ISSUE THREAD

**Issue by kelu27** [nuriel77/iri-playbook#42]
Hi!
Is it possible to monitor multiple nodes?

**Comment by nuriel77** [comment]
Not without some manual work. The current setup configures a single node only.

You could choose one (or more) node(s) and add targets (other node addresses) in `/etc/prometheus/prometheus.yaml`.

Then you would have to make sure those ports are accessible to the "scraping" nodes (where prometheus is running). By default the exporters ports are not exposed on the external interface but on localhost/127.0.0.1, that would also have to be changed.

In addition it would make sense to rev. proxy those on nginx and restrict access only for your nodes (or just use firewall to allow specific IPs).

Hope this makes sense.

**Comment by kelu27** [comment]
Ok thank you! It works for me, will try to make it idempotent.
