### ISSUE TITLE
ERROR! no action detected in task. When running full node monitoring only

### ISSUE THREAD

**Issue by MichaelDevid** [nuriel77/iri-playbook#43]
I get the following error when executing the full node monitoring only command. I had iri, nelson and peer manager already installed. Using Ubuntu 17.04 and latests version of everything as far as I know. 

```
:/opt/iri-playbook$ ansible-playbook -i inventory -v site.yml --skip-tags=iotapm_npm --tags=iri_firewalld,iri_ufw,iotapm_deps,monitoring_role

Using /etc/ansible/ansible.cfg as config file

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/opt/iri-playbook/roles/iri/tasks/main.yml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- import_tasks: role.yml
  ^ here


The error appears to have been in '/opt/iri-playbook/roles/iri/tasks/main.yml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- import_tasks: role.yml
  ^ here
```

**Comment by nuriel77** [comment]
Can you check the version of Ansible? (ansible --version)

It has to be minimum 2.4.0

Check http://iri-playbook.readthedocs.io/en/master/installation.html#installing-ansible

**Comment by MichaelDevid** [comment]
That indeed fixed that issue, thanks for the fast reply. Now at the end of running that command I get an failed task:

`TASK [monitoring : create prometheus datasource in grafana] *****************************************
fatal: [localhost]: FAILED! => {"changed": false, "connection": "close", "content": "{\"message\":\"Basic auth failed\"}", "content_length": "31", "content_type": "application/json; charset=UTF-8", "date": "Sun, 31 Dec 2017 10:32:47 GMT", "json": {"message": "Basic auth failed"}, "msg": "Status code was not [200, 409]: HTTP Error 401: Unauthorized", "redirected": false, "status": 401, "url": "http://localhost:3000/api/datasources"}
	to retry, use: --limit @/opt/iri-playbook/site.retry
`

**Comment by nuriel77** [comment]
Hope this helps: http://iri-playbook.readthedocs.io/en/master/troubleshooting.html#http-error-401-unauthorized-when-running-playbook

**Comment by MichaelDevid** [comment]
Thanks, tried both solutions but passwords seem okay also when I go to http://localhost:5555 I just get an blank page. The title does show Grafana with the logo so I guess the server is running but can't any data. Any more suggestions?

**Comment by nuriel77** [comment]
Grafana is being served by nginx on port 5555. You need to use your external IP instead of localhost, e.g.:
http://your-ext-ip:5555

**Comment by MichaelDevid** [comment]
Also using my ext ip I just get a blank page.

**Comment by nuriel77** [comment]
Can you check some things please?
```sh
lsof -Pni|grep nginx
```
And:
```sh
lsof -Pni:3000
```
Thanks.

**Comment by MichaelDevid** [comment]
`nginx     1155            root    6u  IPv4  24503      0t0  TCP *:9993 (LISTEN)
nginx     1155            root    7u  IPv4  24504      0t0  TCP *:5555 (LISTEN)
nginx     1155            root    8u  IPv4  24505      0t0  TCP *:8811 (LISTEN)
nginx     1155            root    9u  IPv4  24506      0t0  TCP *:8999 (LISTEN)
nginx     1155            root   10u  IPv4  24507      0t0  TCP *:80 (LISTEN)
nginx     1155            root   11u  IPv6  24508      0t0  TCP *:80 (LISTEN)
nginx     1156        www-data    6u  IPv4  24503      0t0  TCP *:9993 (LISTEN)
nginx     1156        www-data    7u  IPv4  24504      0t0  TCP *:5555 (LISTEN)
nginx     1156        www-data    8u  IPv4  24505      0t0  TCP *:8811 (LISTEN)
nginx     1156        www-data    9u  IPv4  24506      0t0  TCP *:8999 (LISTEN)
nginx     1156        www-data   10u  IPv4  24507      0t0  TCP *:80 (LISTEN)
nginx     1156        www-data   11u  IPv6  24508      0t0  TCP *:80 (LISTEN)
nginx     1156        www-data   15u  IPv4  64974      0t0  TCP 192.168.178.17:8811->192.168.178.17:45842 (ESTABLISHED)
nginx     1156        www-data   16u  IPv4  66784      0t0  TCP 192.168.178.17:8811->192.168.178.17:45852 (ESTABLISHED)
nginx     1156        www-data   17u  IPv4  66783      0t0  TCP 192.168.178.17:8811->192.168.178.17:45850 (ESTABLISHED)
nginx     1156        www-data   18u  IPv4  68105      0t0  TCP 127.0.0.1:43610->127.0.0.1:8011 (ESTABLISHED)
nginx     1156        www-data   19u  IPv4  66786      0t0  TCP 192.168.178.17:8811->192.168.178.17:45854 (ESTABLISHED)
nginx     1156        www-data   20u  IPv4  67567      0t0  TCP 192.168.178.17:5555->192.168.178.17:53270 (ESTABLISHED)
nginx     1156        www-data   21u  IPv4  65500      0t0  TCP 192.168.178.17:5555->192.168.178.17:53290 (ESTABLISHED)
nginx     1156        www-data   22u  IPv4  67614      0t0  TCP 192.168.178.17:5555->192.168.178.17:53314 (ESTABLISHED)
nginx     1156        www-data   23u  IPv4  67615      0t0  TCP 192.168.178.17:5555->192.168.178.17:53316 (ESTABLISHED)
nginx     1156        www-data   24u  IPv4  67613      0t0  TCP 192.168.178.17:5555->192.168.178.17:53312 (ESTABLISHED)
nginx     1156        www-data   25u  IPv4  67616      0t0  TCP 192.168.178.17:5555->192.168.178.17:53318 (ESTABLISHED)
nginx     1157        www-data    6u  IPv4  24503      0t0  TCP *:9993 (LISTEN)
nginx     1157        www-data    7u  IPv4  24504      0t0  TCP *:5555 (LISTEN)
nginx     1157        www-data    8u  IPv4  24505      0t0  TCP *:8811 (LISTEN)
nginx     1157        www-data    9u  IPv4  24506      0t0  TCP *:8999 (LISTEN)
nginx     1157        www-data   10u  IPv4  24507      0t0  TCP *:80 (LISTEN)
nginx     1157        www-data   11u  IPv6  24508      0t0  TCP *:80 (LISTEN)
xeelas@xeelas-server:~$ sudo lsof -Pni:3000
COMMAND  PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
grafana 1197 grafana    7u  IPv4  25516      0t0  TCP 127.0.0.1:3000 (LISTEN)
`

**Comment by MichaelDevid** [comment]
xeelas@xeelas-server:~$ sudo lsof -Pni|grep nginx
nginx     1155            root    6u  IPv4  24503      0t0  TCP *:9993 (LISTEN)
nginx     1155            root    7u  IPv4  24504      0t0  TCP *:5555 (LISTEN)
nginx     1155            root    8u  IPv4  24505      0t0  TCP *:8811 (LISTEN)
nginx     1155            root    9u  IPv4  24506      0t0  TCP *:8999 (LISTEN)
nginx     1155            root   10u  IPv4  24507      0t0  TCP *:80 (LISTEN)
nginx     1155            root   11u  IPv6  24508      0t0  TCP *:80 (LISTEN)
nginx     1156        www-data    6u  IPv4  24503      0t0  TCP *:9993 (LISTEN)
nginx     1156        www-data    7u  IPv4  24504      0t0  TCP *:5555 (LISTEN)
nginx     1156        www-data    8u  IPv4  24505      0t0  TCP *:8811 (LISTEN)
nginx     1156        www-data    9u  IPv4  24506      0t0  TCP *:8999 (LISTEN)
nginx     1156        www-data   10u  IPv4  24507      0t0  TCP *:80 (LISTEN)
nginx     1156        www-data   11u  IPv6  24508      0t0  TCP *:80 (LISTEN)
nginx     1156        www-data   15u  IPv4  64974      0t0  TCP 192.168.178.17:8811->192.168.178.17:45842 (ESTABLISHED)
nginx     1156        www-data   16u  IPv4  66784      0t0  TCP 192.168.178.17:8811->192.168.178.17:45852 (ESTABLISHED)
nginx     1156        www-data   17u  IPv4  66783      0t0  TCP 192.168.178.17:8811->192.168.178.17:45850 (ESTABLISHED)
nginx     1156        www-data   18u  IPv4  68105      0t0  TCP 127.0.0.1:43610->127.0.0.1:8011 (ESTABLISHED)
nginx     1156        www-data   19u  IPv4  66786      0t0  TCP 192.168.178.17:8811->192.168.178.17:45854 (ESTABLISHED)
nginx     1156        www-data   20u  IPv4  67567      0t0  TCP 192.168.178.17:5555->192.168.178.17:53270 (ESTABLISHED)
nginx     1156        www-data   21u  IPv4  65500      0t0  TCP 192.168.178.17:5555->192.168.178.17:53290 (ESTABLISHED)
nginx     1156        www-data   22u  IPv4  67614      0t0  TCP 192.168.178.17:5555->192.168.178.17:53314 (ESTABLISHED)
nginx     1156        www-data   23u  IPv4  67615      0t0  TCP 192.168.178.17:5555->192.168.178.17:53316 (ESTABLISHED)
nginx     1156        www-data   24u  IPv4  67613      0t0  TCP 192.168.178.17:5555->192.168.178.17:53312 (ESTABLISHED)
nginx     1156        www-data   25u  IPv4  67616      0t0  TCP 192.168.178.17:5555->192.168.178.17:53318 (ESTABLISHED)
nginx     1157        www-data    6u  IPv4  24503      0t0  TCP *:9993 (LISTEN)
nginx     1157        www-data    7u  IPv4  24504      0t0  TCP *:5555 (LISTEN)
nginx     1157        www-data    8u  IPv4  24505      0t0  TCP *:8811 (LISTEN)
nginx     1157        www-data    9u  IPv4  24506      0t0  TCP *:8999 (LISTEN)
nginx     1157        www-data   10u  IPv4  24507      0t0  TCP *:80 (LISTEN)
nginx     1157        www-data   11u  IPv6  24508      0t0  TCP *:80 (LISTEN)
xeelas@xeelas-server:~$ sudo lsof -Pni:3000
COMMAND  PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
grafana 1197 grafana    7u  IPv4  25516      0t0  TCP 127.0.0.1:3000 (LISTEN)

No idea why its is lined out.

**Comment by nuriel77** [comment]
Ok, sorry, I missed that you said earlier that you get the Grafana title.
Maybe try to run the playbook once more, supply the password you have chosen
```sh
cd /opt/iri-playbook && ansible-playbook -i inventory -v site.yml --skip-tags=iotapm_npm --tags=iri_firewalld,iri_ufw,iotapm_deps,monitoring_role -e iotapm_nginx_password=your-password-here
```
See if it ends without errors and try to login again. Try to click "CTRL-SHIFT-R" on the grafana address on the browser to ensure it refreshes.

**Comment by MichaelDevid** [comment]
Still the same error and a blank page. Any other suggestions? Else I might do a clean install of Ubuntu and do the whole playbook instead of after install of grafana dashboard.

**Comment by nuriel77** [comment]
I noticed that the address in the `lsof` output is a private (internal) address. Maybe that has something to do with it, not sure. I'd really have to take a look on the server and how the configurations were produced, vs. what addresses you are opening in the browser etc.

It would indeed be a safer bet to try a clean install of the whole playbook. Make sure the Ubuntu image (or CentOS) doesn't contain any add ons or pre-installed services like cpanel, plesk etc.

**Comment by MichaelDevid** [comment]
Tried again with this image: http://releases.ubuntu.com/17.04/ but have the same exact problems. I'm not running on a server but a local server in office. 

I ran this command: 
`ansible-playbook -i inventory site.yml`

After that I noticed that grafana-server wasn't installed so I ran:
`ansible-playbook -i inventory -v site.yml --skip-tags=iotapm_npm --tags=iri_firewalld,iri_ufw,iotapm_deps,monitoring_role`

But still same issue with blank page and fatal error on create prometheus datasource in grafana.

**Comment by nuriel77** [comment]
If you started fresh, perhaps better to follow the getting started quickly link:

http://iri-playbook.readthedocs.io/en/master/getting-started-quickly.html#getting-started-quickly

Also I was curious about the IP address. Are you using a server at home? The IP I saw is a private network.

**Comment by MichaelDevid** [comment]
Yeah I'm running it at a server in the office.

**Comment by nuriel77** [comment]
Ok, I am off to party end of year. Hopefully you manage. If not, lets get in touch next year (tomorrow or after tomorrow ;) ) then you can provide me with a description of the environment.

The getting started quickly link is what most users are using. If it doesn't work, something in the environment is different and we'll have to get a look at that.

Happy new year! Best wishes

**Comment by MichaelDevid** [comment]
All right! I'll try that. Gelukkig nieuwjaar :)

**Comment by nuriel77** [comment]
Gelukkig nieuwjaar!
@MichaelDevid any success using the "getting started quickly"?

**Comment by MichaelDevid** [comment]
I tried again with fresh install of Ubuntu Desktop 17.04 and the getting started quickly method but unfortunately the same error. Blank page and same error at the end. Also when starting iri service it fails so I have to start manually. Maybe I should try 16.04 Ubuntu? Or the server version?

**Comment by nuriel77** [comment]
Should be server image indeed.
I will update the requirements in the docs with a link to the correct image.

**Comment by MichaelDevid** [comment]
Right didn't know. Now I tried on 17.04 Server ISO because I had that already installed but still same errors. Should I have 17.10?

**Comment by nuriel77** [comment]
Are you on iotatangle slack? Try to catch me there @nuriel77

**Comment by nuriel77** [comment]
Closing. This was an architecture mis-match. Updated docs to specifically note 64 bit OS. Also added check in the full node installer script https://github.com/nuriel77/iri-playbook/commit/69e1042d3a04b6903badaf4a3f716a45bf1c63b7
