### ISSUE TITLE
Playbook Error

### ISSUE THREAD

**Issue by bitsparq** [nuriel77/iri-playbook#59]
Hi There,

Thanks for creating this, however i found issue just after inputting IOTA Peer Manager password. I used the http://iri-playbook.readthedocs.io/en/master/getting-started-quickly.html.

Here is the message i got:

`Please enter the password with which you will connect to IOTA Peer Mananger
Use a stong password!!! Not 'hello123' or 'iota8181', you get the point ;)
Password: ************
Please repeat: ************
Running playbook...
/usr/bin/unbuffer: 4: exec: tclsh8.6: not found
ERROR! The playbook exited with failure(s). A log has been save here '/tmp/iri-playbook-201801280820.log'

Cheers

**Comment by nuriel77** [comment]
Hi @abeIO . What operating system are you using exactly?

**Comment by bitsparq** [comment]
Ubuntu 16 x 64

**Comment by nuriel77** [comment]
Thanks @abeIO . Maybe not exactly an image from the list?
http://iri-playbook.readthedocs.io/en/master/requirements.html#operating-system

Anyway, the installer installs `unbuffer` before it is used. But it seems that in your case it didn't download the required tclsh package (which makes me suspect the exact type of image you are using).

Can you try to install it manually?
```sh
apt-get install tcl8.6 -y
```
and see if it works?
(try to run `unbuffer ls -l` and see if it errors out)

**Comment by bitsparq** [comment]
Thanks mate.. Done this:
`sudo apt-get install tcl`
Looks good. Thanks
Ref: https://www.howtoinstall.co/en/ubuntu/xenial/tcl
