### ISSUE TITLE
issue with ansible playbook

### ISSUE THREAD

**Issue by gesaleh** [nuriel77/iri-playbook#60]
when i follow the wiki ansible playbook is failing with the following error
```ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/opt/iri-playbook/roles/iri/tasks/main.yml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- import_tasks: role.yml
  ^ here


The error appears to have been in '/opt/iri-playbook/roles/iri/tasks/main.yml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- import_tasks: role.yml
  ^ here
```

the only changes i did is the ngix password

**Comment by nuriel77** [comment]
Hi, Did you miss this part? http://iri-playbook.readthedocs.io/en/master/installation.html#installing-ansible
This error looks like Ansible version is not >=2.4
In any case I'd recommend to try out the 'Getting starting quickly' link which automates all the installation: http://iri-playbook.readthedocs.io/en/master/getting-started-quickly.html

**Comment by nuriel77** [comment]
@gesaleh did you resolve this? Can I close this issue?
