### ISSUE TITLE
Uninstaller (Feature Request)

### ISSUE THREAD

**Issue by oyren** [nuriel77/iri-playbook#65]
Your installer script does so much that I don't have an overview of it. Therefore, an uninstall script would be useful if you want to restore the original.

Great Project

**Comment by nuriel77** [comment]
This can be done (when I have more free time).
Interesting to note is that by accomplishing this issue/feature request https://github.com/nuriel77/iri-playbook/issues/63 it will become much easier to perform a proper clean up.
When installing packages system wide it becomes a little difficult to clean all the dependencies that were installed.
When using containers it becomes somewhat easier (as most dependencies are within the containers).

I am very busy at my day job, and hard to tell when I will have enough time to work on this. Contributions are always welcome.

**Comment by oyren** [comment]
Sure, there's no hurry.

**Comment by nuriel77** [comment]
Added an option to uninstall (most of) the playbook.
