### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by DanHaed** [nuriel77/iri-playbook#72]
I'm getting following error message while installation. 

```
TASK [monitoring : create iota exporter dashboard in grafana] **************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "connection": "close", "content": "{\"message\":\"Invalid alert data. Cannot save dashboard\"}", "content_length": "55", "content_type": "application/json", "date": "Thu, 08 Mar 2018 20:40:39 GMT", "json": {"message": "Invalid alert data. Cannot save dashboard"}, "msg": "Status code was not [200, 412]: HTTP Error 500: Internal Server Error", "redirected": false, "status": 500, "url": "http://localhost:3000/api/dashboards/db"}
        to retry, use: --limit @/opt/iri-playbook/site.retry

PLAY RECAP *****************************************************************************************************************************************
localhost                  : ok=102  changed=2    unreachable=0    failed=1

ERROR! The playbook exited with failure(s). A log has been save here '/tmp/iri-playbook-201803082136.log'
You have new mail in /var/mail/root

```

**Comment by nuriel77** [comment]
Hi @DanHaed 
Grafana has upgraded to version 5 in the recent days. It is incompatible with the iota-exporter dashboard.
As a temporary fix I allowed the installation pass without succeeding to import the dashboard. This means you can still run the installation, however, the dashboard for iota-exporter will not be available.

I am working with the developer of iota-exporter to make the dashboard compatible with the new version. Will let you know when it is ready and how to install it.

For now, please try to re-run the installer command, the installation should pass.

**Comment by nuriel77** [comment]
@DanHaed I applied new fixes to support the changes from Grafana.
https://github.com/nuriel77/iri-playbook/pull/73

Maybe you can try to re-install, that would be the simplest.
Let me know if any more issues after re-install?

**Comment by DanHaed** [comment]
Hi @nuriel77, thank you for yout quick support.
I just tried to Update Monitoring via IRIC and it worked for me.

Thank you
