### ISSUE TITLE
Customized SSH port is not allowed on ufw

### ISSUE THREAD

**Issue by luixxiul** [nuriel77/iri-playbook#82]
**Description:** Customized SSH port is not allowed on ufw. The default 22 port is allowed on ufw, while the ssh port has been customized beforehand. This issue seems to me to be a crucial one as you cannot log in to your server account with SSH client after installation.

**Steps to reproduce the issue:**
1. Log in to your server account with a SSH client
1. Customize SSH port from 22 to something else
2. `sudo systemctl restart ssh`
3. Run the installer following https://iri-playbook.readthedocs.io/en/master/getting-started-quickly.html#run-the-installer

**Expected result:**
The port should be allowed on ufw based on your customization on step 2.

**Actual result:**
Port 22 is allowed on ufw, you're logged out from SSH and cannot log in with SSH again.

**Comment by nuriel77** [comment]
Added:
- check if port is configured to something other than 22 (in /etc/ssh/sshd_config)
- override default port in config

**Comment by nuriel77** [comment]
https://github.com/nuriel77/iri-playbook/commit/8ad4c5ae8f1488b6feab750c42474f0e7e8ee680

**Comment by luixxiul** [comment]
Thanks for the fast fix!
