### ISSUE TITLE
iric update failed

### ISSUE THREAD

**Issue by gitruili** [nuriel77/iri-playbook#97]
TASK [iri : Install some packages] **********************************************************************************************************************************************************
failed: [localhost] (item=[u'maven', u'jq', u'ufw', u'wget', u'lsof', u'curl', u'pv', u'nano', u'sysstat', u'htop', u'pastebinit', u'openssl', u'bsdmainutils', u'whiptail']) => {"changed": false, "item": ["maven", "jq", "ufw", "wget", "lsof", "curl", "pv", "nano", "sysstat", "htop", "pastebinit", "openssl", "bsdmainutils", "whiptail"], "msg": "Failed to update apt cache: W:The repository 'http://asi-fs-n.contabo.net/ubuntu xenial-updates Release' does not have a Release file., W:Data from such a repository can't be authenticated and is therefore potentially dangerous to use., W:See apt-secure(8) manpage for repository creation and user configuration details., W:The repository 'http://asi-fs-n.contabo.net/ubuntu xenial-backports Release' does not have a Release file., W:Data from such a repository can't be authenticated and is therefore potentially dangerous to use., W:See apt-secure(8) manpage for repository creation and user configuration details., W:An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://asi-fs-n.contabo.net/ubuntu xenial InRelease: Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?), W:An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://ppa.launchpad.net/ansible/ansible/ubuntu xenial InRelease: Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?), W:An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://deb.nodesource.com/node_8.x xenial InRelease: At least one invalid signature was encountered., W:An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packagecloud.io/grafana/stable/debian jessie InRelease: At least one invalid signature was encountered., W:Failed to fetch http://asi-fs-n.contabo.net/ubuntu/dists/xenial/InRelease  Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?), W:Failed to fetch http://ppa.launchpad.net/ansible/ansible/ubuntu/dists/xenial/InRelease  Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?), W:Failed to fetch https://deb.nodesource.com/node_8.x/dists/xenial/InRelease  At least one invalid signature was encountered., W:Failed to fetch https://packagecloud.io/grafana/stable/debian/dists/jessie/InRelease  At least one invalid signature was encountered., E:Failed to fetch http://asi-fs-n.contabo.net/ubuntu/dists/xenial-updates/main/binary-amd64/Packages  Write error - write (28: No space left on device), E:Failed to fetch http://asi-fs-n.contabo.net/ubuntu/dists/xenial-backports/main/binary-amd64/Packages  Write error - write (28: No space left on device), E:Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/main/binary-amd64/Packages  Error writing to output file - write (28: No space left on device) Error writing to file - write (28: No space left on device) [IP: 2001:67c:1360:8001::21 80], W:Some index files failed to download. They have been ignored, or old ones used instead."}
        to retry, use: --limit @/opt/iri-playbook/site.retry

PLAY RECAP **********************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1

Updating IRIC failed!!! Check output above for errors. Press ENTER to return to menu.

**Comment by nuriel77** [comment]
@gitruili do you have enough space left on your hard drive?
```
Error writing to output file - write (28: No space left on device) Error writing to file - write (28: No space left on device)
```

You can check that with `df -h`

**Comment by gitruili** [comment]
root@vmi189663:/opt/iri-playbook# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            5.9G     0  5.9G   0% /dev
tmpfs           1.2G  122M  1.1G  11% /run
/dev/sda2       295G  280G     0 100% /
tmpfs           5.9G     0  5.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           5.9G     0  5.9G   0% /sys/fs/cgroup
/dev/sda1       922M   53M  807M   7% /boot


wow, what happend, no space, what can I do?

**Comment by nuriel77** [comment]
Please join Discord IOTA, find #fullnodes channel  where you can get further help on how to clean your drive.
I will close the issue because it is unrelated to any bugs/errors from the playbook itself.
