### ISSUE TITLE
Broken link for JDK

### ISSUE THREAD

**Issue by mrprunen** [nuriel77/iri-playbook#98]
Hi there is jdk broken link
Now in iri.yaml 
http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64.tar.gz
this file has been removed from oracle repositories.

now you can find this
http://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-linux-x64.tar.gz

**Comment by nuriel77** [comment]
@mrprunen thanks for reporting:
Fixed:
https://github.com/nuriel77/iri-playbook/commit/6ec0429346a6c6e896f19ac4ca6a4cd9f457dca7
