### ISSUE TITLE
Install iri-playbook on the Ubuntu (18.04.1) stopped at loss package

### ISSUE THREAD

**Issue by luke1987515** [nuriel77/iri-playbook#99]
Hi,

I just tried to install the playbook on a Ubuntu 18.04.1 (Bionic Beaver) use 

`bash <(curl -s https://raw.githubusercontent.com/nuriel77/iri-playbook/master/fullnode_install.sh)`

, it stopped at

`Reading package lists... Done`
`Building dependency tree`       
`Reading state information... Done`
`E: Unable to locate package expect-dev`
`E: Unable to locate package tcl`

Do I missing same command  before  fullnode_install.sh ?

**Comment by luke1987515** [comment]
I use Ubuntu 16.04.5 is OK.
Thanks.

**Comment by nuriel77** [comment]
Strange, I just tested a fresh install on Ubuntu 18.04.1, didn't get that error.
I tested on Hetzner. Maybe something to do with the image or repositories configured on your node's?

**Comment by luke1987515** [comment]
Is right!
I add 'universe" in default repositories ( /etc/apt/sources.list )
It OK now. Thanks.

Before:
`http://archive.canonical.com/ubuntu bionic main `
`http://archive.canonical.com/ubuntu bionic-security main `
`http://archive.canonical.com/ubuntu bionic-updates main `

After:
`http://archive.canonical.com/ubuntu bionic main  universe`
`http://archive.canonical.com/ubuntu bionic-security main `
`http://archive.canonical.com/ubuntu bionic-updates main `
